### ISSUE TITLE
KeyError: accesslink_api

### ISSUE THREAD

**Issue by cwc101** [JulV94/polar_to_sql#1]
When data is available and running polar_to_sql.py, I'm getting the following.
Have tested in both Python 2.7 and 3 with same result.

 Will append to existing database
Traceback (most recent call last):
  File "polar_to_sql.py", line 217, in <module>
    poltosql.save_new_data()
  File "polar_to_sql.py", line 37, in save_new_data
    self.save_new_exercises(account)
  File "polar_to_sql.py", line 99, in save_new_exercises
    transaction = account["accesslink_api"].training_data.create_transaction(user_id=account["config"]["user_id"],
KeyError: 'accesslink_api'

**Comment by JulV94** [comment]
This means that Python doesn't find the accesslink_api key in the account dictionnary. This entry is created when initializing the PolarToSql object:
```Python
    def __init__(self, configs):
        self.accounts = []
        for db_name, in_configs in configs.items():
            for in_config in in_configs:
                account = dict()
                account["config"] = load_config(in_config)
                account["db_name"] = db_name

                if "access_token" not in account["config"]:
                    print("Authorization is required. Run authorization.py first.")
                    return

                account["accesslist_api"] = AccessLink(client_id=account["config"]["client_id"],
                                                       client_secret=account["config"]["client_secret"])

                self.db_create_if_needed(account["db_name"])
                self.accounts.append(account)
```
If you do not have this key, you probably never reach this line probably because the configs dictionnary is not filled correctly.
Did you created a PolarToSql instance like this?
```Python
configs = {"my_db.db": ["my_config.yml"]}
poltosql = PolarToSql(configs)
```
The `my_db.db` is the output file (will be created if non existing) and the `my_config.yml` is the the same file as for [the example code from Polar.](https://github.com/polarofficial/accesslink-example-python)
